# Generated by Django 5.2.1 on 2025-05-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ism va sharif')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon raqami')),
                ('language_code', models.CharField(choices=[('uz', 'Uzbek'), ('kaa', 'Karakalpak'), ('ru', 'Russian')], default='uz', max_length=3, verbose_name='Til')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
    ]
