# Generated by Django 5.2.1 on 2025-05-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_kaa', models.CharField(max_length=100, verbose_name='Nomi (Qoraqalpoqcha)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (Ruscha)')),
            ],
            options={
                'verbose_name': "Ta'lim bosqichi (OTM)",
                'verbose_name_plural': "Ta'lim bosqichlari (OTM)",
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_kaa', models.CharField(max_length=100, verbose_name='Nomi (Qoraqalpoqcha)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (Ruscha)')),
            ],
            options={
                'verbose_name': "Ta'lim muassasasi turi",
                'verbose_name_plural': "Ta'lim muassasasi turlari",
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name="Nomi (O'zbekcha)")),
                ('name_kaa', models.CharField(max_length=255, verbose_name='Nomi (Qoraqalpoqcha)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Nomi (Ruscha)')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['institution', 'name_uz'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='course_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kurs (bosqich)'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.educationlevel', verbose_name="Ta'lim bosqichi (OTM)"),
        ),
        migrations.AddField(
            model_name='user',
            name='education_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.educationtype', verbose_name="Ta'lim muassasasi turi"),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculty', verbose_name='Fakultet (OTM)'),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name="Nomi (O'zbekcha)")),
                ('name_kaa', models.CharField(max_length=255, verbose_name='Nomi (Qoraqalpoqcha)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Nomi (Ruscha)')),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.educationtype', verbose_name="Ta'lim turi")),
            ],
            options={
                'verbose_name': "Ta'lim muassasasi",
                'verbose_name_plural': "Ta'lim muassasalari",
                'ordering': ['education_type', 'name_uz'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution', verbose_name="Ta'lim muassasasi"),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institution', verbose_name='Muassasa nomi'),
        ),
    ]
