# Generated by Django 5.2.1 on 2025-05-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_educationlevel_educationtype_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationtype',
            name='is_otm',
            field=models.BooleanField(default=False, verbose_name='Bu OTMmi?'),
        ),
    ]
